export default Object.freeze({
  SYMBOL: "symbol",
  SIGN: "sign",
  POWER: "power",
  FRACTION: "fraction",
  TEXT: "text",
  IMAGE: "image",
  SQRT: "sqrt",
  SQRTSYMBOL: "sqrtSymbol",
  CHECKMARK: "checkmark",
  SEMICHECKMARK: "semiCheckmark",
  XMARK: "xmark",
  RIGHT_HANDLE: "rightHandle",
  LEFT_HANDLE: "leftHandle",
});
